export const zh = {
  login: "登录",
  email: "邮箱",
  password: "密码",
  tenant: "租户",
  space: "服务空间",
  object: "服务对象",
  cases: "案例",
  title: "标题",
  category: "类别",
  create: "创建",
  newSpace: "新建服务空间",
  newObject: "新建服务对象",
  objectType: "对象类型",
  newCase: "新建案例",
  caseHome: "案例首页",
  caseHomeHint: "从这里打开已有案例，或创建一个新的独立工作区。",
  caseHint: "选择服务对象，填写案例标题后创建并进入工作区。",
  caseHomeFootnote: "每个案例都有独立的工作区；聊天记录和会话由 ZCode 原生界面管理。",
  caseCount: "个案例",
  noSpace: "还没有服务空间",
  noSpaceHint: "新建案例时可以直接创建服务空间、服务对象和案例。",
  caseDialogHint: "选择服务空间和服务对象，填写标题后即可进入独立工作区。类别留空时使用 general。",
  createSpaceHint: "先创建一个服务空间，再继续填写案例。",
  createSpace: "创建服务空间",
  createObjectInline: "服务对象",
  createObjectHint: "没有合适的对象？在这里填写名称和类型，创建后会自动选中。",
  createObject: "创建并选中对象",
  selectObject: "选择服务对象",
  selectSpaceFirst: "请先选择服务空间",
  titlePlaceholder: "例如：处理客户反馈",
  categoryPlaceholder: "默认 general",
  optional: "可选",
  creating: "创建中…",
  cancel: "取消",
  backToCases: "返回案例",
  switchCase: "切换案例",
  modelSettings: "租户模型设置",
  modelSetupTitle: "租户模型设置",
  modelSetupHint: "管理员在这里配置租户的 AI 服务。保存后，授权案例可以使用同一个模型连接。",
  caseLoading: "正在打开案例工作区…",
  closedCase: "此案例已关闭，无法启动聊天。",
  createAndEnter: "创建并进入",
  open: "打开",
  logout: "退出",
  retry: "重试",
  noCase: "选择或创建案例后开始工作",
  loading: "正在加载…",
  status: "状态",
  context: "案例上下文",
  select: "请选择",
  loginError: "登录失败",
};
export const en = {
  login: "Sign in",
  email: "Email",
  password: "Password",
  tenant: "Tenant",
  space: "Service space",
  object: "Service object",
  cases: "Cases",
  title: "Title",
  category: "Category",
  create: "Create",
  newSpace: "New service space",
  newObject: "New service object",
  objectType: "Object type",
  newCase: "New case",
  caseHome: "Case home",
  caseHomeHint: "Open an existing case or create a separate workspace for a new one.",
  caseHint: "Select a service object, enter a case title, then create the workspace.",
  caseHomeFootnote: "Each case has its own workspace. ZCode manages chats and sessions inside it.",
  caseCount: "cases",
  noSpace: "No service space yet",
  noSpaceHint: "You can create the service space, service object, and case in one flow.",
  caseDialogHint:
    "Choose a service space and service object, then enter a title. A blank category uses general.",
  createSpaceHint: "Create a service space first, then continue with the case.",
  createSpace: "Create service space",
  createObjectInline: "Service object",
  createObjectHint:
    "Need a new object? Enter its name and type here; it will be selected automatically.",
  createObject: "Create and select object",
  selectObject: "Select a service object",
  selectSpaceFirst: "Select a service space first",
  titlePlaceholder: "For example: Resolve customer feedback",
  categoryPlaceholder: "Defaults to general",
  optional: "Optional",
  creating: "Creating…",
  cancel: "Cancel",
  backToCases: "Back to cases",
  switchCase: "Switch case",
  modelSettings: "Tenant model settings",
  modelSetupTitle: "Tenant model settings",
  modelSetupHint:
    "An administrator configures the tenant AI service here. Authorized cases can use the same model connection after it is saved.",
  caseLoading: "Opening case workspace…",
  closedCase: "This case is closed and cannot start chat.",
  createAndEnter: "Create and enter",
  open: "Open",
  logout: "Sign out",
  retry: "Retry",
  noCase: "Select or create a case to begin",
  loading: "Loading…",
  status: "Status",
  context: "Case context",
  select: "Select",
  loginError: "Sign in failed",
};
export const field =
  "min-w-0 rounded-lg border border-input-border bg-input px-3 py-2 text-ui-base text-foreground focus:border-input-border-focused focus:bg-input-focused";
export const button =
  "rounded-lg border border-border bg-surface px-3 py-2 text-ui-base text-foreground hover:bg-surface-hover disabled:opacity-50";
export const primary =
  "rounded-lg bg-primary px-3 py-2 text-ui-base text-primary-foreground disabled:opacity-50";
