export const zh = {
  login: "登录",
  email: "邮箱",
  password: "密码",
  tenant: "租户",
  cancel: "取消",
  modelSettings: "租户模型设置",
  modelSetupTitle: "租户模型设置",
  modelSetupHint: "管理员在这里配置租户的 AI 服务。保存后，客户工作区可以使用同一个模型连接。",
  logout: "退出",
  retry: "重试",
  loading: "正在加载…",
  select: "请选择",
  customers: "客户",
  customerCount: "个客户",
  noCustomer: "还没有客户",
  newCustomer: "新建客户",
  customerDefaultType: "客户",
  customerName: "客户名称",
  customerNamePlaceholder: "例如：华东制造集团",
  customerType: "客户类型",
  customerTypePlaceholder: "例如：企业客户",
  customerLoading: "正在打开工作区…",
  openSettings: "打开企业设置",
  settingsTitle: "企业设置",
  settingsOverview: "概览",
  backToWorkspace: "返回工作区",
  roleAdmin: "管理员",
  roleMember: "成员",
  rename: "重命名",
  deleteCustomer: "删除",
  deleteCustomerConfirm: "删除客户 {name}?工作区目录与全部案例将被移除。",
  customerAdminHint: "客户目录仅租户管理员可维护;新增或删除后,专家运行时会在下次打开时刷新挂载。",
  sharedSkills: "共享 Skill",
  sharedSkillsHint: "对租户全部专家生效(进入其运行时全局层);修改后各专家运行时下次打开时更新。",
  sharedSkillName: "名称",
  sharedSkillContent: "内容（SKILL.md）",
  sharedSkillPlaceholder: "例如：售后工单处理手册",
  sharedSkillContentPlaceholder: "---\nname: playbook\ndescription: …\n---\n# 手册内容",
  createSharedSkill: "创建",
  deleteSharedSkill: "删除",
  noSharedSkill: "还没有共享 Skill",
  sharedSkillFailed: "共享 Skill 操作失败",
  importSkillTitle: "导入为共享 Skill",
  importSkillHint:
    "从你的个人运行时与客户工作区中选择 Skill 导入为租户共享 Skill(原生新建的 Skill 默认在工作区)。",
  importSkillPick: "选择 Skill",
  importSkillFilterPlaceholder: "按名称筛选",
  importSkillOriginHome: "个人",
  importSkillOriginWorkspace: "工作区",
  importSkillAlreadyImported: "已导入",
  importSkillEmpty: "没有可导入的 Skill",
  importSkillAction: "导入",
  importSkillNotFound: "未找到该 Skill",
  save: "保存",
  create: "创建",
  edit: "编辑",
  deleteAction: "删除",
  enabledOn: "已启用",
  enabledOff: "已停用",
  loadFailed: "加载失败",
  modelProviderHint:
    "维护租户的模型供应商目录。启用的供应商会分发到各专家运行时;修改后运行时在下次打开时更新。",
  modelProviderMemberHint: "模型供应商由租户管理员统一配置。",
  newModelProvider: "新增供应商",
  providerKey: "Provider Key",
  providerKeyHint: "创建后不可修改。",
  providerDisplayName: "显示名称",
  providerApiType: "API 协议",
  providerBaseUrl: "Base URL",
  providerApiKey: "API Key",
  providerApiKeyKeepHint: "编辑时留空表示保留当前密钥;密钥仅服务端加密保存,只显示尾号。",
  providerApiKeyPlaceholder: "粘贴 API Key",
  providerModels: "模型列表",
  providerModelsPlaceholder: "逗号或换行分隔,例如 gpt-4o, gpt-4o-mini",
  providerDefaultModel: "默认模型",
  providerDefaultModelUnset: "未指定",
  providerIsDefault: "设为租户默认",
  providerEnabled: "启用",
  defaultBadge: "默认",
  setDefaultAction: "设为默认",
  enableAction: "启用",
  disableAction: "停用",
  testConnection: "连接测试",
  testing: "测试中…",
  testOkSummary: "连接正常 · {count} 个模型",
  testFailed: "连接失败",
  deleteProviderConfirm: "删除供应商 {name}?各专家运行时会在下次打开时移除该供应商。",
  noModelProviders: "还没有供应商",
  noProviderModels: "未配置模型",
  connectors: "连接器",
  connectorHint:
    "租户级 MCP 连接器(系统内置)。启用的连接器会写入各专家运行时;修改后运行时在下次打开时更新。",
  connectorMemberHint: "连接器由租户管理员统一配置。",
  newConnector: "新增连接器",
  connectorKey: "连接器 Key",
  connectorKeyHint: "创建后不可修改。",
  connectorDisplayName: "显示名称",
  connectorUrl: "Endpoint URL",
  connectorHeaderName: "Header 名称",
  connectorSecretEnv: "密钥环境变量",
  connectorSecretEnvHint:
    "需形如 ZCODE_ENTERPRISE_MCP_SECRET_<租户UUID大写无连字符>_<名称>,由运维在网关环境中注入。",
  secretConfigured: "密钥已配置",
  secretNotConfigured: "密钥未配置",
  systemConnectorBadge: "系统内置",
  connectorAuthMode: "认证方式",
  authModeShared: "共享密钥",
  authModeUserOauth: "用户授权 (OAuth)",
  connectorAuthorizeUrl: "Authorize URL",
  connectorTokenUrl: "Token URL",
  connectorClientId: "Client ID",
  connectorClientSecret: "Client Secret",
  connectorClientSecretKeepHint: "机密客户端填写;编辑时留空表示保留当前值,公共客户端可留空。",
  connectorScopes: "Scopes",
  userConnectorBadge: "用户授权",
  connectorConnected: "已连接",
  connectorNotConnected: "未连接",
  connectorConnect: "连接",
  connectorDisconnect: "断开",
  connectorUserAuthHint: "该连接器需要每位专家连接自己的账号后才会进入其运行时。",
  deleteConnectorConfirm: "删除连接器 {name}?各专家运行时会在下次打开时移除该连接器。",
  noConnectors: "还没有连接器",
  users: "用户",
  usersHint:
    "成员是全局身份,此处做租户内的成员管理。全新邮箱会创建账号,已有邮箱直接加入本租户;移除成员只解除本租户关系,账号保留。",
  newUser: "新建成员",
  userDisplayName: "显示名称",
  userInitialPassword: "初始密码",
  userInitialPasswordHint: "全新邮箱必填;已有邮箱加入时留空,沿用其原密码。",
  userRole: "角色",
  userStatus: "状态",
  userStatusActive: "正常",
  userStatusDisabled: "已禁用",
  userJoinedNotice: "已加入现有账号 · {email}",
  userCreatedNotice: "已创建账号 · {email}",
  noUsers: "还没有成员",
  resetPassword: "重置密码",
  resetPasswordKeepHint: "留空表示保留当前密码。",
  removeUser: "移除成员",
  removeUserConfirm: "将 {name} 移出租户?其会话与运行时会立即停止;账号本身保留,可再次加入。",
  customerAccess: "客户可见性",
  customerAccessHint:
    "未设置授权的成员可见全部客户;设置后仅可见所选客户,其运行时挂载同步收窄,变更后立即生效。",
  customerAccessSummaryAll: "全部客户",
  customerAccessSummaryCount: "{count} 个客户",
  customerAccessMode: "可见范围",
  customerAccessModeAll: "全部客户（默认）",
  customerAccessModeSelected: "指定客户",
  customerAccessEmptyInvalid: "指定客户时至少选择一个。",
  customerAccessAdminNote: "管理员始终可见全部客户。",
};
export const en = {
  login: "Sign in",
  email: "Email",
  password: "Password",
  tenant: "Tenant",
  cancel: "Cancel",
  modelSettings: "Tenant model settings",
  modelSetupTitle: "Tenant model settings",
  modelSetupHint:
    "An administrator configures the tenant AI service here. Customer workspaces can use the same model connection after it is saved.",
  logout: "Sign out",
  retry: "Retry",
  loading: "Loading…",
  select: "Select",
  customers: "Customers",
  customerCount: "customers",
  noCustomer: "No customers yet",
  newCustomer: "New customer",
  customerDefaultType: "Customer",
  customerName: "Customer name",
  customerNamePlaceholder: "For example: East China Manufacturing",
  customerType: "Customer type",
  customerTypePlaceholder: "For example: Enterprise",
  customerLoading: "Opening workspace…",
  openSettings: "Open enterprise settings",
  settingsTitle: "Enterprise settings",
  settingsOverview: "Overview",
  backToWorkspace: "Back to workspace",
  roleAdmin: "Admin",
  roleMember: "Member",
  rename: "Rename",
  deleteCustomer: "Delete",
  deleteCustomerConfirm:
    "Delete customer {name}? Its workspace directory and all cases will be removed.",
  customerAdminHint:
    "The customer catalog is admin-only; after changes, expert runtimes refresh mounts on next open.",
  sharedSkills: "Shared Skills",
  sharedSkillsHint:
    "Applies to every expert of the tenant (their runtime global layer); runtimes refresh on next open.",
  sharedSkillName: "Name",
  sharedSkillContent: "Content (SKILL.md)",
  sharedSkillPlaceholder: "For example: support playbook",
  sharedSkillContentPlaceholder: "---\nname: playbook\ndescription: …\n---\n# Playbook",
  createSharedSkill: "Create",
  deleteSharedSkill: "Delete",
  noSharedSkill: "No shared Skills yet",
  sharedSkillFailed: "Shared Skill operation failed",
  importSkillTitle: "Import as shared skill",
  importSkillHint:
    "Pick a skill from your personal runtime or a customer workspace and import it as a tenant shared skill (newly created native skills default to the workspace).",
  importSkillPick: "Choose a skill",
  importSkillFilterPlaceholder: "Filter by name",
  importSkillOriginHome: "Personal",
  importSkillOriginWorkspace: "Workspace",
  importSkillAlreadyImported: "Imported",
  importSkillEmpty: "No importable skills",
  importSkillAction: "Import",
  importSkillNotFound: "Skill not found",
  save: "Save",
  create: "Create",
  edit: "Edit",
  deleteAction: "Delete",
  enabledOn: "Enabled",
  enabledOff: "Disabled",
  loadFailed: "Failed to load",
  modelProviderHint:
    "Maintain the tenant's model provider catalog. Enabled providers are distributed to expert runtimes; runtimes refresh on next open.",
  modelProviderMemberHint: "Model providers are configured by the tenant admin.",
  newModelProvider: "New provider",
  providerKey: "Provider key",
  providerKeyHint: "Immutable after creation.",
  providerDisplayName: "Display name",
  providerApiType: "API protocol",
  providerBaseUrl: "Base URL",
  providerApiKey: "API key",
  providerApiKeyKeepHint:
    "Leave blank while editing to keep the current key; keys are encrypted server-side and only the last four characters are shown.",
  providerApiKeyPlaceholder: "Paste the API key",
  providerModels: "Models",
  providerModelsPlaceholder: "Comma or newline separated, e.g. gpt-4o, gpt-4o-mini",
  providerDefaultModel: "Default model",
  providerDefaultModelUnset: "Unset",
  providerIsDefault: "Tenant default",
  providerEnabled: "Enabled",
  defaultBadge: "Default",
  setDefaultAction: "Set default",
  enableAction: "Enable",
  disableAction: "Disable",
  testConnection: "Test connection",
  testing: "Testing…",
  testOkSummary: "Connected · {count} models",
  testFailed: "Connection failed",
  deleteProviderConfirm: "Delete provider {name}? Expert runtimes drop it on next open.",
  noModelProviders: "No providers yet",
  noProviderModels: "No models configured",
  connectors: "Connectors",
  connectorHint:
    "Tenant MCP connectors (system built-in). Enabled connectors are written into expert runtimes; runtimes refresh on next open.",
  connectorMemberHint: "Connectors are configured by the tenant admin.",
  newConnector: "New connector",
  connectorKey: "Connector key",
  connectorKeyHint: "Immutable after creation.",
  connectorDisplayName: "Display name",
  connectorUrl: "Endpoint URL",
  connectorHeaderName: "Header name",
  connectorSecretEnv: "Secret environment variable",
  connectorSecretEnvHint:
    "Must match ZCODE_ENTERPRISE_MCP_SECRET_<TENANT_UUID_UPPERCASE_NO_HYPHENS>_<NAME>; operators inject it into the gateway environment.",
  secretConfigured: "Secret configured",
  secretNotConfigured: "Secret missing",
  systemConnectorBadge: "System",
  connectorAuthMode: "Auth mode",
  authModeShared: "Shared secret",
  authModeUserOauth: "User authorization (OAuth)",
  connectorAuthorizeUrl: "Authorize URL",
  connectorTokenUrl: "Token URL",
  connectorClientId: "Client ID",
  connectorClientSecret: "Client secret",
  connectorClientSecretKeepHint:
    "For confidential clients; leave blank while editing to keep the current value, public clients may stay blank.",
  connectorScopes: "Scopes",
  userConnectorBadge: "User-authorized",
  connectorConnected: "Connected",
  connectorNotConnected: "Not connected",
  connectorConnect: "Connect",
  connectorDisconnect: "Disconnect",
  connectorUserAuthHint:
    "Each expert must connect their own account before this connector enters their runtime.",
  deleteConnectorConfirm: "Delete connector {name}? Expert runtimes drop it on next open.",
  noConnectors: "No connectors yet",
  users: "Users",
  usersHint:
    "Members are global identities; this tab manages this tenant's memberships. A brand-new email creates an account, an existing email simply joins; removing a member only ends this tenant's relationship and keeps the account.",
  newUser: "New member",
  userDisplayName: "Display name",
  userInitialPassword: "Initial password",
  userInitialPasswordHint:
    "Required for a brand-new email; leave blank when an existing email joins — it keeps its password.",
  userRole: "Role",
  userStatus: "Status",
  userStatusActive: "Active",
  userStatusDisabled: "Disabled",
  userJoinedNotice: "Joined an existing account · {email}",
  userCreatedNotice: "Account created · {email}",
  noUsers: "No members yet",
  resetPassword: "Reset password",
  resetPasswordKeepHint: "Leave blank to keep the current password.",
  removeUser: "Remove member",
  removeUserConfirm:
    "Remove {name} from the tenant? Their sessions and runtimes stop immediately; the account itself is kept and can join again.",
  customerAccess: "Customer visibility",
  customerAccessHint:
    "Members without grants see every customer; once granted, only the selected customers are visible and their runtime mounts narrow accordingly — effective immediately.",
  customerAccessSummaryAll: "All customers",
  customerAccessSummaryCount: "{count} customers",
  customerAccessMode: "Visibility",
  customerAccessModeAll: "All customers (default)",
  customerAccessModeSelected: "Selected customers",
  customerAccessEmptyInvalid: "Select at least one customer.",
  customerAccessAdminNote: "Admins always see every customer.",
} satisfies Record<keyof typeof zh, string>;
export const field =
  "min-w-0 rounded-lg border border-input-border bg-input px-3 py-2 text-ui-base text-foreground focus:border-input-border-focused focus:bg-input-focused";
export const button =
  "rounded-lg border border-border bg-surface px-3 py-2 text-ui-base text-foreground hover:bg-surface-hover disabled:opacity-50";
export const primary =
  "rounded-lg bg-primary px-3 py-2 text-ui-base text-primary-foreground disabled:opacity-50";
export const badge =
  "rounded-full border border-border bg-surface px-2 py-0.5 text-ui-xs text-foreground-subtle";
export const chip =
  "rounded border border-border bg-surface px-1.5 py-0.5 font-mono text-ui-xs text-foreground-subtle";
